export const initialMemberForm = {
  memberFirstName: "",
  memberLastName: "",
  memberUserName: "",
  memberPassword: "",
  memberConfPassword: "",
  memberEmail: "",
  memberPhone: "",
  memberAddress: "",
  memberCity: "",
  memberState: "",
  memberZip: "",
  memberautoRenew: false,
  membertermsAgree: false,
};
